### PR TITLE
optimization.

### PR DESCRIPTION
**Pull request by REALHaydenGaming**
- I cant run week 7 (fully) so I added this here. -- Clears all unused memory as well.

Im a based Chromebook user.

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by Raltyro** [comment]
There is no such thing as Paths.unusedStoredMemory, and its already optimized enough, i dont see your point here so im just going to close this

**Comment by REALHaydenGaming** [comment]
> There is no such thing as Paths.unusedStoredMemory, and its already optimized enough, i dont see your point here so im just going to close this

I forgot to fix a bug in it oops, but uhhhhhh its already laggy for some pcs, even with all of the settings on, it doesn't help.

**Comment by REALHaydenGaming** [comment]
> > There is no such thing as Paths.unusedStoredMemory, and its already optimized enough, i dont see your point here so im just going to close this
> 
> I forgot to fix a bug in it oops, but uhhhhhh its already laggy for some pcs, even with all of the settings on, it doesn't help.

Screenshot 2022-12-18 3 58 46 PM
Screenshot 2022-12-18 3 59 43 PM
Screenshot 2022-12-18 3 59 51 PM

**Comment by Raltyro** [comment]
Alright, reopening this, please mention me again whenever you finished it
also Week 7 have unloaded graphics on cutscenes is because of Hardware Caching

**Comment by REALHaydenGaming** [comment]
@Raltyro

**Comment by Raltyro** [comment]
alright nevermind... your using these functions in the wrong way
and clearUnusedMemory is already on Playstate

forgot to say it could be lagging on your end is because of Streaming Music option as it reloads the buffers multiple times for to synchronize, i will rewrite the descriptions for these options later

**Pull request closed without merging**
